name: "Build for Windows"
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install MinGW"
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake 
          msystem: mingw64
      - name: "Add MinGW to PATH"
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      - name: "Configure CMake"
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE="Release" 
      - name: "Build with MinGW Make"
        run: |
          cmake --build build
      - name: "Upload Bin Artifact"
        uses: actions/upload-artifact@v4
        with: 
          name: Windows Executables 
          path: build/bin/
      - name: "Upload Lib Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: Windows Libraries
          path: build/lib/
